[package]
name = "krustlet-cri"
version = "0.1.0"
authors = ["kflansburg <kevin.flansburg@gmail.com>"]
edition = "2018"

[dependencies]
kubelet = { version = "*", git="https://github.com/deislabs/krustlet.git", features = ['cli'] }
tokio = { version = "0.2", features = ["macros", "net"] }
kube = "0.33"
env_logger = "0.7"
anyhow = "*"
async-trait = "0.1"
log = "0.4"
tonic = { version = "*" }
prost = "*"
tower = "*"
k8s-openapi = "*"
k8s-cri = "0.1.2" 
