apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "$(date) Hello World"; sleep 10; done']
  nodeSelector:
    kubernetes.io/hostname: krustlet-cri 
